disabled_rules:
  - closing_brace
  - opening_brace
  - identifier_name
  - type_name
  - force_cast
  - force_unwrapping
  - trailing_comma
  - empty_enum_arguments
  - force_try

included:
  - Source
  - Specs
excluded:
  - Carthage

trailing_whitespace:
  severity: error

line_length:
  warning: 135
  error: 135

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 1200